# Generated by Django 5.2.14 on 2026-05-27 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("bank", models.CharField(max_length=120)),
                ("iban", models.CharField(max_length=34, unique=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[("personal", "Personal / household"), ("business", "Business")], max_length=10
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("current", "Current"),
                            ("savings", "Savings"),
                            ("term", "Term deposit"),
                            ("credit", "Credit"),
                        ],
                        default="current",
                        max_length=10,
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["scope", "name"],
            },
        ),
        migrations.CreateModel(
            name="StatementImport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "bank",
                    models.CharField(
                        choices=[("credito_agricola", "Crédito Agrícola"), ("cgd", "Caixa Geral de Depósitos")],
                        max_length=20,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("personal", "Personal / household"), ("business", "Business")], max_length=10
                    ),
                ),
                ("statement_number", models.CharField(blank=True, max_length=20)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("source_file", models.CharField(blank=True, max_length=255)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-period_end", "-imported_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("income", "Income"),
                            ("expense", "Expense"),
                            ("transfer", "Transfer"),
                            ("investment", "Investment"),
                            ("tax", "Tax"),
                            ("other", "Other"),
                        ],
                        default="expense",
                        max_length=12,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="finance.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["kind", "name"],
            },
        ),
        migrations.CreateModel(
            name="BalanceSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("as_of", models.DateField()),
                ("current_total", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("savings_total", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("investments_total", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("mortgage_balance", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="finance.statementimport",
                    ),
                ),
            ],
            options={
                "ordering": ["-as_of"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("value_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("balance", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("dedupe_key", models.CharField(editable=False, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="finance.account"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="finance.category",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="finance.statementimport",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "id"],
                "indexes": [models.Index(fields=["account", "date"], name="finance_tra_account_588697_idx")],
            },
        ),
    ]
