# Generated by Django 5.2.14 on 2026-05-27 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("match_text", models.CharField(max_length=120)),
                (
                    "sign",
                    models.CharField(
                        choices=[("any", "Any"), ("credit", "Credit (money in)"), ("debit", "Debit (money out)")],
                        default="any",
                        max_length=6,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        blank=True,
                        choices=[("personal", "Personal / household"), ("business", "Business")],
                        max_length=10,
                    ),
                ),
                ("priority", models.IntegerField(default=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rules", to="finance.category"
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "id"],
            },
        ),
    ]
