# Generated by Django 5.2.14 on 2026-05-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_categoryrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="role",
            field=models.CharField(
                choices=[
                    ("house", "Household (holds the mortgage)"),
                    ("personal", "Personal"),
                    ("business", "Business"),
                ],
                default="personal",
                max_length=10,
            ),
        ),
    ]
