# Generated by Django 5.2.14 on 2026-05-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_populate_account_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryrule",
            name="effective_from",
            field=models.DateField(blank=True, null=True),
        ),
    ]
