# Generated by Django 5.2.14 on 2026-05-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_categoryrule_effective_from"),
    ]

    operations = [
        migrations.CreateModel(
            name="IgnoreRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("match_text", models.CharField(max_length=120, unique=True)),
                ("note", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["match_text"],
            },
        ),
    ]
