# Generated by Django 5.2.14 on 2026-05-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0006_ignorerule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="kind",
            field=models.CharField(
                choices=[
                    ("current", "Current"),
                    ("savings", "Savings"),
                    ("term", "Term deposit"),
                    ("credit", "Credit"),
                    ("brokerage", "Brokerage"),
                ],
                default="current",
                max_length=10,
            ),
        ),
    ]
