# Generated by Django 5.2.14 on 2026-05-29 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0008_set_degiro_kind_brokerage"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("as_of", models.DateField()),
                ("market_value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_snapshots",
                        to="finance.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-as_of"],
                "constraints": [models.UniqueConstraint(fields=("account", "as_of"), name="unique_portfolio_snapshot")],
            },
        ),
    ]
